/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testpractice_jni_HelloNative */

#ifndef _Included_com_example_testpractice_jni_HelloNative
#define _Included_com_example_testpractice_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testpractice_jni_HelloNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testpractice_jni_HelloNative_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
